import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tom' at '20/08/16 13:24' with Gradle 2.7
 *
 * @author tom, @date 20/08/16 13:24
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ConsumerApplication classUnderTest = new ConsumerApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
